# -*- coding: utf-8 -*-
"""From_Email_Company_extractor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTzyqyoVnLhl3Raq73xbc4aKMdMK3RIn
"""

import imaplib
import email

m = imaplib.IMAP4_SSL("imap.gmail.com", 993)
m.login("mumbai@bestroadways.com","Xx:-119/2,20125")
m.select('"[Gmail]/All Mail"')

# import pandas as pd
# # m.to_csv(r'E:\Best_Email_Output\mail.xls')
# m.to_excel('mail.xlsx',sheet_name='Sheet1', index=False,engine='xlsxwriter')

result, data = m.uid('search', None, "ALL") # search all email and return uids
if result == 'OK':
  for num in data[0].split():
    result, data = m.uid('fetch', num, '(RFC822)')
    if result == 'OK':
      email_message = email.message_from_bytes(data[0][1])    # raw email text including headers
      print('From:' + email_message['From'])

m.close()